version: '2'

services:

  istex-view-rp:
    container_name: istex-view-rp
    image: nginx:1.11.4
    links:
      - istex-view-www
    volumes:
      - ./logs/:/var/log/nginx
      - ./ngnix/debug.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 45445:80

  istex-view-www:
    container_name: istex-view-www
    image: node:4.4.0
    working_dir: /app
    volumes:
      - .:/app
    stdin_open: true  # to be able to use CTRL+C to stop the debug
    environment:
      NODE_ENV: "development"
      DEBUG: ${DEBUG}
    ports:
      - 8080:8080
      - 3123:3123
    command: npm run dev